### PR TITLE
Add support to Tizen

### PR DESCRIPTION
**Pull request by dead**
### How to use:
 - Install Tizen Studio (latest version)
 - Install the Native CLI, Web CLI, TV and Certficate Manager packages.  (Using the "Package Manager")
 - Set `TIZEN_CLI` environment variable to the Tizen CLI folder. (Usually `<TIZEN_STUDIO>/tools/ide/bin`)
 - Setup a certificate using the "Certficate Manager"
 - Execute `react-tv run-tizen` inside a react-tv application 😄 

### Benchmark
emulator-x86_64_2017-11-17_23-25-26

### CODE REVIEW

**Comment by raphamorim** [comment]
Amazing @dead!
Can you update the README and add info about Tizen?

I'll test this PR on this weekend. 👍  ❤️

**Comment by raphamorim** [comment]
I'll close #63 #58 for finish `0.3.0` and then I'll work on it.

**Comment by JosePedroDiasSky** [comment]
🙌

**Comment by dead** [comment]
@raphamorim done 😄

**Comment by raphamorim** [comment]
@dead I solved other conflicts and create another PR with your commits.
I'll go on with #104 (some things to do yet: adjust for `macos` env). 

When it ends/merged I'll notify you and ask if it's still working on Windows Env.

**Comment by Blinnikov** [comment]
Hi, @dead.
Could you please share benchmark code you've used?

@raphamorim can we include it in the repo to allow any user run performance tests?

**Comment by dead** [comment]
@Blinnikov 
@raphamorim removed the benchmark code. I think it wasn't a real benchmark...

**Comment by raphamorim** [comment]
Yeah, isn't a real benchmark.
Maybe a good benchmark is check memory usage (footprint or other way) based on renders updates.

**Pull request closed without merging**
